"""empty message

Revision ID: 085552103ad3
Revises: 9505f6bf1c2e
Create Date: 2025-02-23 19:49:37.848209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085552103ad3'
down_revision: Union[str, None] = '9505f6bf1c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tickets', 'AF_analista_asignado',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tickets', 'AF_analista_asignado',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###
