"""Added auth tables

Revision ID: 3dd192f5e561
Revises: 
Create Date: 2025-02-01 23:11:25.012410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd192f5e561'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Roles',
    sa.Column('AF_codigo', sa.String(length=4), nullable=False),
    sa.Column('AF_nombre', sa.String(length=16), nullable=False),
    sa.Column('AF_descripcion', sa.String(length=128), nullable=False),
    sa.Column('BO_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('AF_codigo')
    )
    op.create_table('Usuarios',
    sa.Column('AF_alias', sa.String(length=16), nullable=False),
    sa.Column('AF_nombre', sa.String(length=64), nullable=False),
    sa.Column('AF_apellido', sa.String(length=64), nullable=False),
    sa.Column('NU_cedula', sa.Integer(), nullable=False),
    sa.Column('AF_correo', sa.String(length=128), nullable=False),
    sa.Column('AF_contraseña', sa.String(length=256), nullable=False),
    sa.Column('AF_correo_alternativo', sa.String(length=128), nullable=True),
    sa.Column('AF_telefono_casa', sa.String(length=16), nullable=True),
    sa.Column('AF_telefono_personal', sa.String(length=16), nullable=False),
    sa.Column('TI_fecha_ingreso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('TI_ultimo_inicio_sesion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('AF_codigo_rol', sa.String(length=4), nullable=False),
    sa.Column('AF_usuario_supervisor', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['AF_codigo_rol'], ['Roles.AF_codigo'], ),
    sa.ForeignKeyConstraint(['AF_usuario_supervisor'], ['Usuarios.AF_alias'], ),
    sa.PrimaryKeyConstraint('AF_alias')
    )
    op.create_table('Auditorias',
    sa.Column('NU_historico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AF_tabla', sa.String(length=64), nullable=False),
    sa.Column('AF_accion', sa.Enum('Crear', 'Modificar', 'Eliminar', name='acciones_auditoria'), nullable=False),
    sa.Column('AF_id_registro', sa.String(length=64), nullable=False),
    sa.Column('AF_campo_modificado', sa.String(length=64), nullable=True),
    sa.Column('AF_valor_viejo', sa.String(length=128), nullable=True),
    sa.Column('AF_valor_nuevo', sa.String(length=128), nullable=True),
    sa.Column('TI_fecha_accion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('AF_usuario_modificador', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['AF_usuario_modificador'], ['Usuarios.AF_alias'], ),
    sa.PrimaryKeyConstraint('NU_historico')
    )
    op.create_table('IniciosDeSesion',
    sa.Column('NU_numero', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AF_usuario', sa.String(length=16), nullable=False),
    sa.Column('TI_fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('TI_fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['AF_usuario'], ['Usuarios.AF_alias'], ),
    sa.PrimaryKeyConstraint('NU_numero')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IniciosDeSesion')
    op.drop_table('Auditorias')
    op.drop_table('Usuarios')
    op.drop_table('Roles')
    # ### end Alembic commands ###
