"""Added document tables

Revision ID: 907569ea568e
Revises: 6593f11b09f2
Create Date: 2025-02-06 23:13:03.693839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907569ea568e'
down_revision: Union[str, None] = '6593f11b09f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DocumentosAdjuntos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AF_nombre', sa.String(length=256), nullable=False),
    sa.Column('TI_fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ArchivosAdjuntosIncidencias',
    sa.Column('NU_incidencia', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NU_id_documento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NU_id_documento'], ['DocumentosAdjuntos.id'], ),
    sa.ForeignKeyConstraint(['NU_incidencia'], ['Incidencias.NU_incidencia'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ArchivosAdjuntosTickets',
    sa.Column('NU_ticket', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NU_id_documento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NU_id_documento'], ['DocumentosAdjuntos.id'], ),
    sa.ForeignKeyConstraint(['NU_ticket'], ['Tickets.NU_ticket'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ArchivosAdjuntosTrazas',
    sa.Column('NU_traza', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NU_id_documento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NU_id_documento'], ['DocumentosAdjuntos.id'], ),
    sa.ForeignKeyConstraint(['NU_traza'], ['TrazaDeTickets.NU_traza'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ArchivosAdjuntosTrazas')
    op.drop_table('ArchivosAdjuntosTickets')
    op.drop_table('ArchivosAdjuntosIncidencias')
    op.drop_table('DocumentosAdjuntos')
    # ### end Alembic commands ###
