"""empty message

Revision ID: 9505f6bf1c2e
Revises: b3ef6539ab29
Create Date: 2025-02-23 15:25:16.716813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9505f6bf1c2e'
down_revision: Union[str, None] = 'b3ef6539ab29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Incidencias_AF_titulo'), 'Incidencias', ['AF_titulo'], unique=False)
    op.create_index(op.f('ix_Incidencias_NU_incidencia'), 'Incidencias', ['NU_incidencia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Incidencias_NU_incidencia'), table_name='Incidencias')
    op.drop_index(op.f('ix_Incidencias_AF_titulo'), table_name='Incidencias')
    # ### end Alembic commands ###
