"""Modified user table

Revision ID: b08286f23ae1
Revises: 3dd192f5e561
Create Date: 2025-02-01 23:53:19.273594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08286f23ae1'
down_revision: Union[str, None] = '3dd192f5e561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuarios', sa.Column('BO_activo', sa.Boolean(), nullable=False))
    op.alter_column('Usuarios', 'AF_apellido',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('Usuarios', 'AF_telefono_personal',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.create_unique_constraint(None, 'Usuarios', ['NU_cedula'])
    op.create_unique_constraint(None, 'Usuarios', ['AF_correo'])
    op.create_unique_constraint(None, 'Usuarios', ['AF_correo_alternativo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Usuarios', type_='unique')
    op.drop_constraint(None, 'Usuarios', type_='unique')
    op.drop_constraint(None, 'Usuarios', type_='unique')
    op.alter_column('Usuarios', 'AF_telefono_personal',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('Usuarios', 'AF_apellido',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('Usuarios', 'BO_activo')
    # ### end Alembic commands ###
