"""empty message

Revision ID: b3ef6539ab29
Revises: 
Create Date: 2025-02-19 21:42:52.727008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ef6539ab29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categorias',
    sa.Column('NU_nivel_jerarquia', sa.Integer(), nullable=False),
    sa.Column('AF_codigo_categoria_padre', sa.String(length=8), nullable=True),
    sa.Column('AF_codigo', sa.String(length=8), nullable=False),
    sa.Column('AF_nombre', sa.String(length=64), nullable=False),
    sa.Column('AF_descripcion', sa.String(length=128), nullable=False),
    sa.Column('BO_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['AF_codigo_categoria_padre'], ['Categorias.AF_codigo'], ),
    sa.PrimaryKeyConstraint('AF_codigo')
    )
    op.create_table('DocumentosAdjuntos',
    sa.Column('NU_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AF_nombre', sa.String(length=256), nullable=False),
    sa.Column('TI_fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('NU_id')
    )
    op.create_table('Incidencias',
    sa.Column('NU_incidencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AF_titulo', sa.String(length=128), nullable=False),
    sa.Column('AF_descripcion', sa.String(length=5096), nullable=False),
    sa.Column('TI_fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('AF_nombre_reportador', sa.String(length=128), nullable=False),
    sa.Column('AF_correo_reportador', sa.String(length=128), nullable=False),
    sa.Column('BO_archivado', sa.Boolean(), nullable=False),
    sa.Column('AF_motivo_archivado', sa.String(length=256), nullable=True),
    sa.Column('TI_fecha_archivado', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('NU_incidencia')
    )
    op.create_table('Prioridades',
    sa.Column('AF_color', sa.String(length=16), nullable=False),
    sa.Column('NU_prioridad', sa.Integer(), nullable=False),
    sa.Column('AF_codigo', sa.String(length=16), nullable=False),
    sa.Column('AF_descripcion', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('AF_codigo'),
    sa.UniqueConstraint('AF_color'),
    sa.UniqueConstraint('NU_prioridad')
    )
    op.create_table('Roles',
    sa.Column('AF_codigo', sa.String(length=4), nullable=False),
    sa.Column('AF_nombre', sa.String(length=16), nullable=False),
    sa.Column('AF_descripcion', sa.String(length=128), nullable=False),
    sa.Column('BO_activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('AF_codigo')
    )
    op.create_table('ArchivosAdjuntosIncidencias',
    sa.Column('NU_incidencia', sa.Integer(), nullable=False),
    sa.Column('NU_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NU_id_documento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NU_id_documento'], ['DocumentosAdjuntos.NU_id'], ),
    sa.ForeignKeyConstraint(['NU_incidencia'], ['Incidencias.NU_incidencia'], ),
    sa.PrimaryKeyConstraint('NU_id')
    )
    op.create_table('Usuarios',
    sa.Column('AF_alias', sa.String(length=16), nullable=False),
    sa.Column('AF_nombre', sa.String(length=64), nullable=False),
    sa.Column('AF_apellido', sa.String(length=64), nullable=True),
    sa.Column('NU_cedula', sa.Integer(), nullable=False),
    sa.Column('AF_correo', sa.String(length=128), nullable=False),
    sa.Column('AF_contraseña', sa.String(length=256), nullable=False),
    sa.Column('AF_correo_alternativo', sa.String(length=128), nullable=True),
    sa.Column('AF_telefono_casa', sa.String(length=16), nullable=True),
    sa.Column('AF_telefono_personal', sa.String(length=32), nullable=True),
    sa.Column('TI_fecha_ingreso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('TI_ultimo_inicio_sesion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('AF_codigo_rol', sa.String(length=4), nullable=False),
    sa.Column('AF_usuario_supervisor', sa.String(length=16), nullable=True),
    sa.Column('BO_activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['AF_codigo_rol'], ['Roles.AF_codigo'], ),
    sa.ForeignKeyConstraint(['AF_usuario_supervisor'], ['Usuarios.AF_alias'], ),
    sa.PrimaryKeyConstraint('AF_alias'),
    sa.UniqueConstraint('AF_correo'),
    sa.UniqueConstraint('AF_correo_alternativo'),
    sa.UniqueConstraint('NU_cedula')
    )
    op.create_table('Auditorias',
    sa.Column('NU_historico', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AF_tabla', sa.String(length=64), nullable=False),
    sa.Column('AF_accion', sa.Enum('Crear', 'Modificar', 'Eliminar', name='acciones_auditoria'), nullable=False),
    sa.Column('AF_id_registro', sa.String(length=64), nullable=False),
    sa.Column('AF_campo_modificado', sa.String(length=64), nullable=True),
    sa.Column('AF_valor_viejo', sa.String(length=128), nullable=True),
    sa.Column('AF_valor_nuevo', sa.String(length=128), nullable=True),
    sa.Column('TI_fecha_accion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('AF_usuario_modificador', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['AF_usuario_modificador'], ['Usuarios.AF_alias'], ),
    sa.PrimaryKeyConstraint('NU_historico')
    )
    op.create_table('IniciosDeSesion',
    sa.Column('NU_numero', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AF_usuario', sa.String(length=16), nullable=False),
    sa.Column('TI_fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('TI_fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['AF_usuario'], ['Usuarios.AF_alias'], ),
    sa.PrimaryKeyConstraint('NU_numero')
    )
    op.create_table('Tickets',
    sa.Column('NU_ticket', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AF_titulo', sa.String(length=128), nullable=False),
    sa.Column('AF_descripcion', sa.String(length=5096), nullable=False),
    sa.Column('TI_fecha_asignacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('TI_fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('AF_estatus', sa.Enum('Nuevo', 'Asignado', 'En Curso', 'Resuelto', 'Cerrado', name='estatus_tickets'), nullable=False),
    sa.Column('NU_incidencia', sa.Integer(), nullable=False),
    sa.Column('AF_codigo_categoria', sa.String(length=8), nullable=False),
    sa.Column('AF_codigo_prioridad', sa.String(length=16), nullable=False),
    sa.Column('AF_analista_asignado', sa.String(length=16), nullable=False),
    sa.Column('BO_archivado', sa.Boolean(), nullable=False),
    sa.Column('AF_motivo_archivado', sa.String(length=256), nullable=True),
    sa.Column('TI_fecha_archivado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['AF_analista_asignado'], ['Usuarios.AF_alias'], ),
    sa.ForeignKeyConstraint(['AF_codigo_categoria'], ['Categorias.AF_codigo'], ),
    sa.ForeignKeyConstraint(['AF_codigo_prioridad'], ['Prioridades.AF_codigo'], ),
    sa.ForeignKeyConstraint(['NU_incidencia'], ['Incidencias.NU_incidencia'], ),
    sa.PrimaryKeyConstraint('NU_ticket'),
    sa.UniqueConstraint('NU_incidencia')
    )
    op.create_table('ArchivosAdjuntosTickets',
    sa.Column('NU_ticket', sa.Integer(), nullable=False),
    sa.Column('NU_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NU_id_documento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NU_id_documento'], ['DocumentosAdjuntos.NU_id'], ),
    sa.ForeignKeyConstraint(['NU_ticket'], ['Tickets.NU_ticket'], ),
    sa.PrimaryKeyConstraint('NU_id')
    )
    op.create_table('TrazaDeTickets',
    sa.Column('NU_traza', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NU_correlativo', sa.Integer(), nullable=False),
    sa.Column('AF_actividad', sa.String(length=64), nullable=False),
    sa.Column('AF_descripcion', sa.String(length=1024), nullable=False),
    sa.Column('TI_fecha_actividad', sa.DateTime(timezone=True), nullable=False),
    sa.Column('BO_anulada', sa.Boolean(), nullable=False),
    sa.Column('NU_ticket', sa.Integer(), nullable=False),
    sa.Column('AF_usuario_realizador', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['AF_usuario_realizador'], ['Usuarios.AF_alias'], ),
    sa.ForeignKeyConstraint(['NU_ticket'], ['Tickets.NU_ticket'], ),
    sa.PrimaryKeyConstraint('NU_traza')
    )
    op.create_table('ArchivosAdjuntosTrazas',
    sa.Column('NU_traza', sa.Integer(), nullable=False),
    sa.Column('NU_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NU_id_documento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NU_id_documento'], ['DocumentosAdjuntos.NU_id'], ),
    sa.ForeignKeyConstraint(['NU_traza'], ['TrazaDeTickets.NU_traza'], ),
    sa.PrimaryKeyConstraint('NU_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ArchivosAdjuntosTrazas')
    op.drop_table('TrazaDeTickets')
    op.drop_table('ArchivosAdjuntosTickets')
    op.drop_table('Tickets')
    op.drop_table('IniciosDeSesion')
    op.drop_table('Auditorias')
    op.drop_table('Usuarios')
    op.drop_table('ArchivosAdjuntosIncidencias')
    op.drop_table('Roles')
    op.drop_table('Prioridades')
    op.drop_table('Incidencias')
    op.drop_table('DocumentosAdjuntos')
    op.drop_table('Categorias')
    # ### end Alembic commands ###
